# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileverification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='mobile_no',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
