# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileverification', '0003_auto_20170201_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='OTP',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
